apiVersion: v1
kind: Service
metadata:
  name: qdrant
spec:
  selector:
    app: qdrant
  ports:
    - protocol: TCP
      port: 6333
      targetPort: 6333
      name: restapi
    - protocol: TCP
      port: 6334
      targetPort: 6334
      name: grcpapi
  type: LoadBalancer

